version: "1"
services:
  big-data:
    container_name: big-data
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./data:/app/data
      - ./notebook:/app/notebook
